
/**
 * @file check_node.c
 *
 * Functions needed by chkm traversal.
 *
 * THIS FILE HAS BEEN GENERATED USING
 * $Id: check_node.c.xsl 15657 2007-11-13 13:57:30Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

/**
 * @defgroup check Touch all Tree Functions to catch every node, son and attribute
 *
 * Functions needed by free traversal.
 *
 * @{
 */


#include "check_node.h"
#include "check_attribs.h"
#include "tree_basic.h"
#include "traverse.h"
#include "dbug.h"

#define CHKMTRAV( node, info) (node != NULL) ? TRAVdo( node, info) : node
#define CHKMCOND( node, info)                                    \
    ? CHKMTRAV( node, info)                                      \
    : (node)



/*******************************************************************************
 *
 * @fn CHKMpostfun
 *
 * This is the postfun function of the CHKM Traversal
 *
 ******************************************************************************/
node           *
CHKMpostfun(node * arg_node, info * arg_info)
{
	DBUG_ENTER("CHKMpostfun");

	DBUG_RETURN(arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMassign
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node Assign node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMassign(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMassign");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	ASSIGN_LET(arg_node) = CHKMTRAV(ASSIGN_LET(arg_node), arg_info);
	ASSIGN_EXPR(arg_node) = CHKMTRAV(ASSIGN_EXPR(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMbinop
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node BinOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMbinop(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMbinop");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	BINOP_LEFT(arg_node) = CHKMTRAV(BINOP_LEFT(arg_node), arg_info);
	BINOP_RIGHT(arg_node) = CHKMTRAV(BINOP_RIGHT(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMbool
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node Bool node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMbool(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMbool");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMcast
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node Cast node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMcast(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMcast");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	CAST_EXPR(arg_node) = CHKMTRAV(CAST_EXPR(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMdeclarations
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node Declarations node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMdeclarations(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMdeclarations");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	DECLARATIONS_NEXT(arg_node) = CHKMTRAV(DECLARATIONS_NEXT(arg_node), arg_info);
	DECLARATIONS_DECLARATION(arg_node) = CHKMTRAV(DECLARATIONS_DECLARATION(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMdowhile
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node DoWhile node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMdowhile(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMdowhile");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	DOWHILE_STMTS(arg_node) = CHKMTRAV(DOWHILE_STMTS(arg_node), arg_info);
	DOWHILE_WHILE(arg_node) = CHKMTRAV(DOWHILE_WHILE(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMelse
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node Else node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMelse(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMelse");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	ELSE_STMTS(arg_node) = CHKMTRAV(ELSE_STMTS(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMerror
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node Error node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMerror(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMerror");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	ERROR_NEXT(arg_node) = CHKMTRAV(ERROR_NEXT(arg_node), arg_info);
	ERROR_MESSAGE(arg_node) = CHKMattribString(ERROR_MESSAGE(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMexpressions
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node Expressions node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMexpressions(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMexpressions");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	EXPRESSIONS_NEXT(arg_node) = CHKMTRAV(EXPRESSIONS_NEXT(arg_node), arg_info);
	EXPRESSIONS_EXPR(arg_node) = CHKMTRAV(EXPRESSIONS_EXPR(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMfloat
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node Float node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMfloat(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMfloat");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMfor
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node For node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMfor(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMfor");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	FOR_ASSIGN(arg_node) = CHKMTRAV(FOR_ASSIGN(arg_node), arg_info);
	FOR_EXPR(arg_node) = CHKMTRAV(FOR_EXPR(arg_node), arg_info);
	FOR_EXPROPT(arg_node) = CHKMTRAV(FOR_EXPROPT(arg_node), arg_info);
	FOR_STMTS(arg_node) = CHKMTRAV(FOR_STMTS(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMfunc
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node Func node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMfunc(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMfunc");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	FUNC_NAME(arg_node) = CHKMattribString(FUNC_NAME(arg_node), arg_info);
	FUNC_FUNCBODY(arg_node) = CHKMTRAV(FUNC_FUNCBODY(arg_node), arg_info);
	FUNC_PARAMETERS(arg_node) = CHKMTRAV(FUNC_PARAMETERS(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMfuncbody
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node FuncBody node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMfuncbody(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMfuncbody");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	FUNCBODY_STMTS(arg_node) = CHKMTRAV(FUNCBODY_STMTS(arg_node), arg_info);
	FUNCBODY_VARDECLARATIONS(arg_node) = CHKMTRAV(FUNCBODY_VARDECLARATIONS(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMfunctioncallexpr
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node FunctionCallExpr node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMfunctioncallexpr(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMfunctioncallexpr");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	FUNCTIONCALLEXPR_NAME(arg_node) = CHKMattribString(FUNCTIONCALLEXPR_NAME(arg_node), arg_info);
	FUNCTIONCALLEXPR_EXPRESSIONS(arg_node) = CHKMTRAV(FUNCTIONCALLEXPR_EXPRESSIONS(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMfunctioncallstmt
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node FunctionCallStmt node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMfunctioncallstmt(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMfunctioncallstmt");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	FUNCTIONCALLSTMT_NAME(arg_node) = CHKMattribString(FUNCTIONCALLSTMT_NAME(arg_node), arg_info);
	FUNCTIONCALLSTMT_EXPRESSIONS(arg_node) = CHKMTRAV(FUNCTIONCALLSTMT_EXPRESSIONS(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMglobaldec
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node GlobalDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMglobaldec(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMglobaldec");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	GLOBALDEC_NAME(arg_node) = CHKMattribString(GLOBALDEC_NAME(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMglobaldef
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node GlobalDef node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMglobaldef(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMglobaldef");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	GLOBALDEF_NAME(arg_node) = CHKMattribString(GLOBALDEF_NAME(arg_node), arg_info);
	GLOBALDEF_ASSIGN(arg_node) = CHKMTRAV(GLOBALDEF_ASSIGN(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMif
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node If node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMif(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMif");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	IF_ELSE(arg_node) = CHKMTRAV(IF_ELSE(arg_node), arg_info);
	IF_EXPR(arg_node) = CHKMTRAV(IF_EXPR(arg_node), arg_info);
	IF_STMTS(arg_node) = CHKMTRAV(IF_STMTS(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMmodule
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node Module node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMmodule(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMmodule");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	MODULE_DECLARATIONS(arg_node) = CHKMTRAV(MODULE_DECLARATIONS(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMmonop
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node MonOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMmonop(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMmonop");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	MONOP_EXPR(arg_node) = CHKMTRAV(MONOP_EXPR(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMnum
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node Num node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMnum(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMnum");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMparameters
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node Parameters node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMparameters(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMparameters");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	PARAMETERS_NEXT(arg_node) = CHKMTRAV(PARAMETERS_NEXT(arg_node), arg_info);
	PARAMETERS_NAME(arg_node) = CHKMattribString(PARAMETERS_NAME(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMreturn
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node Return node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMreturn(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMreturn");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	RETURN_EXPR(arg_node) = CHKMTRAV(RETURN_EXPR(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMstmts
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node Stmts node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMstmts(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMstmts");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	STMTS_NEXT(arg_node) = CHKMTRAV(STMTS_NEXT(arg_node), arg_info);
	STMTS_STMT(arg_node) = CHKMTRAV(STMTS_STMT(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMsymboltableentry
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node SymbolTableEntry node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMsymboltableentry(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMsymboltableentry");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMvar
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node Var node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMvar(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMvar");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	VAR_NAME(arg_node) = CHKMattribString(VAR_NAME(arg_node), arg_info);
	VAR_DECLARATION(arg_node) = CHKMattribLink(VAR_DECLARATION(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMvarlet
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node VarLet node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMvarlet(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMvarlet");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	VARLET_NEXT(arg_node) = CHKMTRAV(VARLET_NEXT(arg_node), arg_info);
	VARLET_NAME(arg_node) = CHKMattribString(VARLET_NAME(arg_node), arg_info);
	VARLET_DECLARATION(arg_node) = CHKMattribLink(VARLET_DECLARATION(arg_node), arg_info);
	VARLET_ASSIGN(arg_node) = CHKMTRAV(VARLET_ASSIGN(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn CHKMwhile
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node While node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *CHKMwhile(node * arg_node, info * arg_info) {
	DBUG_ENTER("CHKMwhile");
	NODE_ERROR(arg_node) = CHKMTRAV(NODE_ERROR(arg_node), arg_info);
	WHILE_EXPR(arg_node) = CHKMTRAV(WHILE_EXPR(arg_node), arg_info);
	WHILE_STMTS(arg_node) = CHKMTRAV(WHILE_STMTS(arg_node), arg_info);
	DBUG_RETURN(arg_node);
}
/**
 * @}
 */
