
/**
 * @file free_node.c
 *
 * Functions needed by free traversal.
 *
 * THIS FILE HAS BEEN GENERATED USING
 * $Id: free_node.c.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

/**
 * @defgroup free Free Tree Functions.
 *
 * Functions needed by free traversal.
 *
 * @{
 */


#include "free.h"
#include "free_node.h"
#include "free_attribs.h"
#include "free_info.h"
#include "tree_basic.h"
#include "traverse.h"
#include "str.h"
#include "memory.h"
#include "dbug.h"

#define FREETRAV( node, info) (node != NULL) ? TRAVdo( node, info) : node
#define FREECOND( node, info)                                    \
  (INFO_FREE_FLAG( info) != arg_node)                            \
    ? FREETRAV( node, info)                                      \
    : (node)


/** <!--******************************************************************-->
 *
 * @fn FREEassign
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Assign node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEassign(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEassign");
	DBUG_PRINT("FREE", ("Processing node N_assign at " F_PTR, arg_node));
	ASSIGN_LET(arg_node) = FREETRAV(ASSIGN_LET(arg_node), arg_info);
	ASSIGN_EXPR(arg_node) = FREETRAV(ASSIGN_EXPR(arg_node), arg_info);
	result = NULL;
	arg_node->sons.N_assign = MEMfree(arg_node->sons.N_assign);
	arg_node->attribs.N_assign = MEMfree(arg_node->attribs.N_assign);
	DBUG_PRINT("FREE", ("Processing node N_assign at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEbinop
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node BinOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEbinop(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEbinop");
	DBUG_PRINT("FREE", ("Processing node N_binop at " F_PTR, arg_node));
	BINOP_LEFT(arg_node) = FREETRAV(BINOP_LEFT(arg_node), arg_info);
	BINOP_RIGHT(arg_node) = FREETRAV(BINOP_RIGHT(arg_node), arg_info);
	result = NULL;
	arg_node->sons.N_binop = MEMfree(arg_node->sons.N_binop);
	arg_node->attribs.N_binop = MEMfree(arg_node->attribs.N_binop);
	DBUG_PRINT("FREE", ("Processing node N_binop at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEbool
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Bool node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEbool(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEbool");
	DBUG_PRINT("FREE", ("Processing node N_bool at " F_PTR, arg_node));
	result = NULL;
	arg_node->sons.N_bool = MEMfree(arg_node->sons.N_bool);
	arg_node->attribs.N_bool = MEMfree(arg_node->attribs.N_bool);
	DBUG_PRINT("FREE", ("Processing node N_bool at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEcast
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Cast node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEcast(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEcast");
	DBUG_PRINT("FREE", ("Processing node N_cast at " F_PTR, arg_node));
	CAST_EXPR(arg_node) = FREETRAV(CAST_EXPR(arg_node), arg_info);
	result = NULL;
	arg_node->sons.N_cast = MEMfree(arg_node->sons.N_cast);
	arg_node->attribs.N_cast = MEMfree(arg_node->attribs.N_cast);
	DBUG_PRINT("FREE", ("Processing node N_cast at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEdeclarations
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Declarations node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEdeclarations(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEdeclarations");
	DBUG_PRINT("FREE", ("Processing node N_declarations at " F_PTR, arg_node));
	DECLARATIONS_NEXT(arg_node) = FREECOND(DECLARATIONS_NEXT(arg_node), arg_info);
	DECLARATIONS_DECLARATION(arg_node) = FREETRAV(DECLARATIONS_DECLARATION(arg_node), arg_info);
	result = DECLARATIONS_NEXT(arg_node);
	arg_node->sons.N_declarations = MEMfree(arg_node->sons.N_declarations);
	arg_node->attribs.N_declarations = MEMfree(arg_node->attribs.N_declarations);
	DBUG_PRINT("FREE", ("Processing node N_declarations at " F_PTR, arg_node));
	arg_node = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEdowhile
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node DoWhile node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEdowhile(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEdowhile");
	DBUG_PRINT("FREE", ("Processing node N_dowhile at " F_PTR, arg_node));
	DOWHILE_STMTS(arg_node) = FREETRAV(DOWHILE_STMTS(arg_node), arg_info);
	DOWHILE_WHILE(arg_node) = FREETRAV(DOWHILE_WHILE(arg_node), arg_info);
	result = NULL;
	arg_node->sons.N_dowhile = MEMfree(arg_node->sons.N_dowhile);
	arg_node->attribs.N_dowhile = MEMfree(arg_node->attribs.N_dowhile);
	DBUG_PRINT("FREE", ("Processing node N_dowhile at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEelse
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Else node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEelse(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEelse");
	DBUG_PRINT("FREE", ("Processing node N_else at " F_PTR, arg_node));
	ELSE_STMTS(arg_node) = FREETRAV(ELSE_STMTS(arg_node), arg_info);
	result = NULL;
	arg_node->sons.N_else = MEMfree(arg_node->sons.N_else);
	arg_node->attribs.N_else = MEMfree(arg_node->attribs.N_else);
	DBUG_PRINT("FREE", ("Processing node N_else at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEerror
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Error node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEerror(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEerror");
	DBUG_PRINT("FREE", ("Processing node N_error at " F_PTR, arg_node));
	ERROR_NEXT(arg_node) = FREECOND(ERROR_NEXT(arg_node), arg_info);
	ERROR_MESSAGE(arg_node) = FREEattribString(ERROR_MESSAGE(arg_node), arg_node);
	result = ERROR_NEXT(arg_node);
	arg_node->sons.N_error = MEMfree(arg_node->sons.N_error);
	arg_node->attribs.N_error = MEMfree(arg_node->attribs.N_error);
	DBUG_PRINT("FREE", ("Processing node N_error at " F_PTR, arg_node));
	arg_node = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEexpressions
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Expressions node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEexpressions(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEexpressions");
	DBUG_PRINT("FREE", ("Processing node N_expressions at " F_PTR, arg_node));
	EXPRESSIONS_NEXT(arg_node) = FREECOND(EXPRESSIONS_NEXT(arg_node), arg_info);
	EXPRESSIONS_EXPR(arg_node) = FREETRAV(EXPRESSIONS_EXPR(arg_node), arg_info);
	result = EXPRESSIONS_NEXT(arg_node);
	arg_node->sons.N_expressions = MEMfree(arg_node->sons.N_expressions);
	arg_node->attribs.N_expressions = MEMfree(arg_node->attribs.N_expressions);
	DBUG_PRINT("FREE", ("Processing node N_expressions at " F_PTR, arg_node));
	arg_node = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEfloat
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Float node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEfloat(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEfloat");
	DBUG_PRINT("FREE", ("Processing node N_float at " F_PTR, arg_node));
	result = NULL;
	arg_node->sons.N_float = MEMfree(arg_node->sons.N_float);
	arg_node->attribs.N_float = MEMfree(arg_node->attribs.N_float);
	DBUG_PRINT("FREE", ("Processing node N_float at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEfor
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node For node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEfor(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEfor");
	DBUG_PRINT("FREE", ("Processing node N_for at " F_PTR, arg_node));
	FOR_ASSIGN(arg_node) = FREETRAV(FOR_ASSIGN(arg_node), arg_info);
	FOR_EXPR(arg_node) = FREETRAV(FOR_EXPR(arg_node), arg_info);
	FOR_EXPROPT(arg_node) = FREETRAV(FOR_EXPROPT(arg_node), arg_info);
	FOR_STMTS(arg_node) = FREETRAV(FOR_STMTS(arg_node), arg_info);
	result = NULL;
	arg_node->sons.N_for = MEMfree(arg_node->sons.N_for);
	arg_node->attribs.N_for = MEMfree(arg_node->attribs.N_for);
	DBUG_PRINT("FREE", ("Processing node N_for at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEfunc
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Func node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEfunc(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEfunc");
	DBUG_PRINT("FREE", ("Processing node N_func at " F_PTR, arg_node));
	FUNC_NAME(arg_node) = FREEattribString(FUNC_NAME(arg_node), arg_node);
	FUNC_FUNCBODY(arg_node) = FREETRAV(FUNC_FUNCBODY(arg_node), arg_info);
	FUNC_PARAMETERS(arg_node) = FREETRAV(FUNC_PARAMETERS(arg_node), arg_info);
	result = NULL;
	arg_node->sons.N_func = MEMfree(arg_node->sons.N_func);
	arg_node->attribs.N_func = MEMfree(arg_node->attribs.N_func);
	DBUG_PRINT("FREE", ("Processing node N_func at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEfuncbody
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FuncBody node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEfuncbody(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEfuncbody");
	DBUG_PRINT("FREE", ("Processing node N_funcbody at " F_PTR, arg_node));
	FUNCBODY_STMTS(arg_node) = FREETRAV(FUNCBODY_STMTS(arg_node), arg_info);
	FUNCBODY_VARDECLARATIONS(arg_node) = FREETRAV(FUNCBODY_VARDECLARATIONS(arg_node), arg_info);
	result = NULL;
	arg_node->sons.N_funcbody = MEMfree(arg_node->sons.N_funcbody);
	arg_node->attribs.N_funcbody = MEMfree(arg_node->attribs.N_funcbody);
	DBUG_PRINT("FREE", ("Processing node N_funcbody at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEfunctioncallexpr
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FunctionCallExpr node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEfunctioncallexpr(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEfunctioncallexpr");
	DBUG_PRINT("FREE", ("Processing node N_functioncallexpr at " F_PTR, arg_node));
	FUNCTIONCALLEXPR_NAME(arg_node) = FREEattribString(FUNCTIONCALLEXPR_NAME(arg_node), arg_node);
	FUNCTIONCALLEXPR_EXPRESSIONS(arg_node) = FREETRAV(FUNCTIONCALLEXPR_EXPRESSIONS(arg_node), arg_info);
	result = NULL;
	arg_node->sons.N_functioncallexpr = MEMfree(arg_node->sons.N_functioncallexpr);
	arg_node->attribs.N_functioncallexpr = MEMfree(arg_node->attribs.N_functioncallexpr);
	DBUG_PRINT("FREE", ("Processing node N_functioncallexpr at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEfunctioncallstmt
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FunctionCallStmt node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEfunctioncallstmt(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEfunctioncallstmt");
	DBUG_PRINT("FREE", ("Processing node N_functioncallstmt at " F_PTR, arg_node));
	FUNCTIONCALLSTMT_NAME(arg_node) = FREEattribString(FUNCTIONCALLSTMT_NAME(arg_node), arg_node);
	FUNCTIONCALLSTMT_EXPRESSIONS(arg_node) = FREETRAV(FUNCTIONCALLSTMT_EXPRESSIONS(arg_node), arg_info);
	result = NULL;
	arg_node->sons.N_functioncallstmt = MEMfree(arg_node->sons.N_functioncallstmt);
	arg_node->attribs.N_functioncallstmt = MEMfree(arg_node->attribs.N_functioncallstmt);
	DBUG_PRINT("FREE", ("Processing node N_functioncallstmt at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEglobaldec
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node GlobalDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEglobaldec(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEglobaldec");
	DBUG_PRINT("FREE", ("Processing node N_globaldec at " F_PTR, arg_node));
	GLOBALDEC_NAME(arg_node) = FREEattribString(GLOBALDEC_NAME(arg_node), arg_node);
	result = NULL;
	arg_node->sons.N_globaldec = MEMfree(arg_node->sons.N_globaldec);
	arg_node->attribs.N_globaldec = MEMfree(arg_node->attribs.N_globaldec);
	DBUG_PRINT("FREE", ("Processing node N_globaldec at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEglobaldef
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node GlobalDef node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEglobaldef(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEglobaldef");
	DBUG_PRINT("FREE", ("Processing node N_globaldef at " F_PTR, arg_node));
	GLOBALDEF_NAME(arg_node) = FREEattribString(GLOBALDEF_NAME(arg_node), arg_node);
	GLOBALDEF_ASSIGN(arg_node) = FREETRAV(GLOBALDEF_ASSIGN(arg_node), arg_info);
	result = NULL;
	arg_node->sons.N_globaldef = MEMfree(arg_node->sons.N_globaldef);
	arg_node->attribs.N_globaldef = MEMfree(arg_node->attribs.N_globaldef);
	DBUG_PRINT("FREE", ("Processing node N_globaldef at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEif
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node If node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEif(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEif");
	DBUG_PRINT("FREE", ("Processing node N_if at " F_PTR, arg_node));
	IF_ELSE(arg_node) = FREETRAV(IF_ELSE(arg_node), arg_info);
	IF_EXPR(arg_node) = FREETRAV(IF_EXPR(arg_node), arg_info);
	IF_STMTS(arg_node) = FREETRAV(IF_STMTS(arg_node), arg_info);
	result = NULL;
	arg_node->sons.N_if = MEMfree(arg_node->sons.N_if);
	arg_node->attribs.N_if = MEMfree(arg_node->attribs.N_if);
	DBUG_PRINT("FREE", ("Processing node N_if at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEmodule
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Module node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEmodule(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEmodule");
	DBUG_PRINT("FREE", ("Processing node N_module at " F_PTR, arg_node));
	MODULE_DECLARATIONS(arg_node) = FREETRAV(MODULE_DECLARATIONS(arg_node), arg_info);
	result = NULL;
	arg_node->sons.N_module = MEMfree(arg_node->sons.N_module);
	arg_node->attribs.N_module = MEMfree(arg_node->attribs.N_module);
	DBUG_PRINT("FREE", ("Processing node N_module at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEmonop
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node MonOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEmonop(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEmonop");
	DBUG_PRINT("FREE", ("Processing node N_monop at " F_PTR, arg_node));
	MONOP_EXPR(arg_node) = FREETRAV(MONOP_EXPR(arg_node), arg_info);
	result = NULL;
	arg_node->sons.N_monop = MEMfree(arg_node->sons.N_monop);
	arg_node->attribs.N_monop = MEMfree(arg_node->attribs.N_monop);
	DBUG_PRINT("FREE", ("Processing node N_monop at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEnum
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Num node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEnum(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEnum");
	DBUG_PRINT("FREE", ("Processing node N_num at " F_PTR, arg_node));
	result = NULL;
	arg_node->sons.N_num = MEMfree(arg_node->sons.N_num);
	arg_node->attribs.N_num = MEMfree(arg_node->attribs.N_num);
	DBUG_PRINT("FREE", ("Processing node N_num at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEparameters
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Parameters node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEparameters(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEparameters");
	DBUG_PRINT("FREE", ("Processing node N_parameters at " F_PTR, arg_node));
	PARAMETERS_NEXT(arg_node) = FREECOND(PARAMETERS_NEXT(arg_node), arg_info);
	PARAMETERS_NAME(arg_node) = FREEattribString(PARAMETERS_NAME(arg_node), arg_node);
	result = PARAMETERS_NEXT(arg_node);
	arg_node->sons.N_parameters = MEMfree(arg_node->sons.N_parameters);
	arg_node->attribs.N_parameters = MEMfree(arg_node->attribs.N_parameters);
	DBUG_PRINT("FREE", ("Processing node N_parameters at " F_PTR, arg_node));
	arg_node = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEreturn
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Return node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEreturn(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEreturn");
	DBUG_PRINT("FREE", ("Processing node N_return at " F_PTR, arg_node));
	RETURN_EXPR(arg_node) = FREETRAV(RETURN_EXPR(arg_node), arg_info);
	result = NULL;
	arg_node->sons.N_return = MEMfree(arg_node->sons.N_return);
	arg_node->attribs.N_return = MEMfree(arg_node->attribs.N_return);
	DBUG_PRINT("FREE", ("Processing node N_return at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEstmts
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Stmts node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEstmts(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEstmts");
	DBUG_PRINT("FREE", ("Processing node N_stmts at " F_PTR, arg_node));
	STMTS_NEXT(arg_node) = FREECOND(STMTS_NEXT(arg_node), arg_info);
	STMTS_STMT(arg_node) = FREETRAV(STMTS_STMT(arg_node), arg_info);
	result = STMTS_NEXT(arg_node);
	arg_node->sons.N_stmts = MEMfree(arg_node->sons.N_stmts);
	arg_node->attribs.N_stmts = MEMfree(arg_node->attribs.N_stmts);
	DBUG_PRINT("FREE", ("Processing node N_stmts at " F_PTR, arg_node));
	arg_node = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEsymboltableentry
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node SymbolTableEntry node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEsymboltableentry(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEsymboltableentry");
	DBUG_PRINT("FREE", ("Processing node N_symboltableentry at " F_PTR, arg_node));
	result = NULL;
	arg_node->sons.N_symboltableentry = MEMfree(arg_node->sons.N_symboltableentry);
	arg_node->attribs.N_symboltableentry = MEMfree(arg_node->attribs.N_symboltableentry);
	DBUG_PRINT("FREE", ("Processing node N_symboltableentry at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEvar
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Var node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEvar(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEvar");
	DBUG_PRINT("FREE", ("Processing node N_var at " F_PTR, arg_node));
	VAR_NAME(arg_node) = FREEattribString(VAR_NAME(arg_node), arg_node);
	VAR_DECLARATION(arg_node) = FREEattribLink(VAR_DECLARATION(arg_node), arg_node);
	result = NULL;
	arg_node->sons.N_var = MEMfree(arg_node->sons.N_var);
	arg_node->attribs.N_var = MEMfree(arg_node->attribs.N_var);
	DBUG_PRINT("FREE", ("Processing node N_var at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEvarlet
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node VarLet node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEvarlet(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEvarlet");
	DBUG_PRINT("FREE", ("Processing node N_varlet at " F_PTR, arg_node));
	VARLET_NEXT(arg_node) = FREECOND(VARLET_NEXT(arg_node), arg_info);
	VARLET_NAME(arg_node) = FREEattribString(VARLET_NAME(arg_node), arg_node);
	VARLET_DECLARATION(arg_node) = FREEattribLink(VARLET_DECLARATION(arg_node), arg_node);
	VARLET_ASSIGN(arg_node) = FREETRAV(VARLET_ASSIGN(arg_node), arg_info);
	result = VARLET_NEXT(arg_node);
	arg_node->sons.N_varlet = MEMfree(arg_node->sons.N_varlet);
	arg_node->attribs.N_varlet = MEMfree(arg_node->attribs.N_varlet);
	DBUG_PRINT("FREE", ("Processing node N_varlet at " F_PTR, arg_node));
	arg_node = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn FREEwhile
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node While node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *FREEwhile(node * arg_node, info * arg_info) {
	node           *result = NULL;
	DBUG_ENTER("FREEwhile");
	DBUG_PRINT("FREE", ("Processing node N_while at " F_PTR, arg_node));
	WHILE_EXPR(arg_node) = FREETRAV(WHILE_EXPR(arg_node), arg_info);
	WHILE_STMTS(arg_node) = FREETRAV(WHILE_STMTS(arg_node), arg_info);
	result = NULL;
	arg_node->sons.N_while = MEMfree(arg_node->sons.N_while);
	arg_node->attribs.N_while = MEMfree(arg_node->attribs.N_while);
	DBUG_PRINT("FREE", ("Processing node N_while at " F_PTR, arg_node));
	result = MEMfree(arg_node);
	DBUG_RETURN(result);
}
/**
 * @}
 */
