
/**
 * @file eval.c
 *
 * Functions needed for compiling
 *
 * THIS FILE HAS BEEN GENERATED USING
 * $Id: free_node.c.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

/**
 * @defgroup comp Compilation functions.
 *
 * Functions needed for compiling.
 *
 * @{
 */


#include "eval.h"
#include "traverse.h"
#include "dbug.h"


/** <!--******************************************************************-->
 *
 * @fn EVALassign
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Assign node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALassign(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALassign");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALbinop
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node BinOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALbinop(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALbinop");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALbool
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Bool node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALbool(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALbool");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALcast
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Cast node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALcast(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALcast");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALdeclarations
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Declarations node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALdeclarations(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALdeclarations");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALdowhile
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node DoWhile node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALdowhile(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALdowhile");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALelse
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Else node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALelse(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALelse");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALerror
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Error node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALerror(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALerror");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALexpressions
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Expressions node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALexpressions(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALexpressions");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALfloat
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Float node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALfloat(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALfloat");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALfor
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node For node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALfor(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALfor");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALfunc
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Func node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALfunc(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALfunc");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALfuncbody
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FuncBody node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALfuncbody(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALfuncbody");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALfunctioncallexpr
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FunctionCallExpr node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALfunctioncallexpr(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALfunctioncallexpr");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALfunctioncallstmt
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FunctionCallStmt node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALfunctioncallstmt(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALfunctioncallstmt");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALglobaldec
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node GlobalDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALglobaldec(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALglobaldec");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALglobaldef
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node GlobalDef node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALglobaldef(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALglobaldef");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALif
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node If node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALif(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALif");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALmodule
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Module node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALmodule(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALmodule");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALmonop
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node MonOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALmonop(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALmonop");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALnum
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Num node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALnum(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALnum");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALparameters
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Parameters node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALparameters(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALparameters");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALreturn
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Return node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALreturn(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALreturn");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALstmts
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Stmts node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALstmts(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALstmts");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALsymboltableentry
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node SymbolTableEntry node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALsymboltableentry(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALsymboltableentry");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALvar
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Var node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALvar(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALvar");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALvarlet
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node VarLet node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALvarlet(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALvarlet");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/** <!--******************************************************************-->
 *
 * @fn EVALwhile
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node While node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *EVALwhile(node * arg_node, info * arg_info) {
	DBUG_ENTER("EVALwhile");
	arg_node = TRAVcont(arg_node, arg_info);
	DBUG_RETURN(arg_node);
}
/**
 * @}
 */
