
/**
 * @file traverse_tables.c
 *
 * This file defines the function tables for traversal.
 *
 * THIS FILE HAS BEEN GENERATED USING
 * $Id: traverse_tables.c.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#include "traverse_tables.h"
#include "traverse_helper.h"
#include "print.h"
#include "copy_node.h"
#include "free_node.h"
#include "check.h"
#include "rename_identifiers.h"
#include "sum_ints.h"
#include "sum_opts.h"
#include "sum_identifiers.h"
#include "opt_sub.h"


travtables_t	travtables = {
	/* TR_undefined */
	{&TRAVerror
	,&TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror}

	/* TR_prt */
	,{&TRAVerror, &PRTmodule, &PRTdeclarations, &PRTfunc, &PRTglobaldec, &PRTglobaldef, &PRTfuncbody, &PRTparameters, &PRTstmts, &PRTassign, &PRTif, &PRTelse, &PRTwhile, &PRTdowhile, &PRTfor, &PRTreturn, &PRTexpressions, &PRTfunctioncallstmt, &PRTbinop, &PRTmonop, &PRTvarlet, &PRTvar, &PRTcast, &PRTfunctioncallexpr, &PRTnum, &PRTfloat, &PRTbool, &PRTsymboltableentry, &PRTerror}

	/* TR_copy */
	,{&TRAVerror, &COPYmodule, &COPYdeclarations, &COPYfunc, &COPYglobaldec, &COPYglobaldef, &COPYfuncbody, &COPYparameters, &COPYstmts, &COPYassign, &COPYif, &COPYelse, &COPYwhile, &COPYdowhile, &COPYfor, &COPYreturn, &COPYexpressions, &COPYfunctioncallstmt, &COPYbinop, &COPYmonop, &COPYvarlet, &COPYvar, &COPYcast, &COPYfunctioncallexpr, &COPYnum, &COPYfloat, &COPYbool, &COPYsymboltableentry, &COPYerror}

	/* TR_free */
	,{&TRAVerror, &FREEmodule, &FREEdeclarations, &FREEfunc, &FREEglobaldec, &FREEglobaldef, &FREEfuncbody, &FREEparameters, &FREEstmts, &FREEassign, &FREEif, &FREEelse, &FREEwhile, &FREEdowhile, &FREEfor, &FREEreturn, &FREEexpressions, &FREEfunctioncallstmt, &FREEbinop, &FREEmonop, &FREEvarlet, &FREEvar, &FREEcast, &FREEfunctioncallexpr, &FREEnum, &FREEfloat, &FREEbool, &FREEsymboltableentry, &FREEerror}

	/* TR_chk */
	,{&TRAVerror, &CHKmodule, &CHKdeclarations, &CHKfunc, &CHKglobaldec, &CHKglobaldef, &CHKfuncbody, &CHKparameters, &CHKstmts, &CHKassign, &CHKif, &CHKelse, &CHKwhile, &CHKdowhile, &CHKfor, &CHKreturn, &CHKexpressions, &CHKfunctioncallstmt, &CHKbinop, &CHKmonop, &CHKvarlet, &CHKvar, &CHKcast, &CHKfunctioncallexpr, &CHKnum, &CHKfloat, &CHKbool, &CHKsymboltableentry, &CHKerror}

	/* TR_ri */
	,{&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &RIvarlet, &RIvar, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons}

	/* TR_si */
	,{&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &SInum, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons}

	/* TR_so */
	,{&TRAVerror, &SOmodule, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &SObinop, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons}

	/* TR_sid */
	,{&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &SIDvarlet, &SIDvar, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons}

	/* TR_os */
	,{&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &OSbinop, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons}
};

preposttable_t	pretable = {
	NULL
	,NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
};

preposttable_t	posttable = {
	NULL
	,NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
};

const char     *travnames[10] = {
	"unknown"
	,"prt", "copy", "free", "chk", "ri", "si", "so", "sid", "os"
};
